use customer_behaviour;
show tables;
describe customer_data;
select * from customer_data limit 10;

## What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) from customer_data group by gender;


## Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount 
from customer_data 
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_data);

##Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) 
from customer_data 
group by item_purchased 
order by avg(review_rating) desc limit 5;

## Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) from customer_data where shipping_type in ('standard','Express') group by shipping_type;

##Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select count(customer_id) as 'total_customer', subscription_status,avg(purchase_amount) as Avg_amount, 
sum(purchase_amount) as total_amount from customer_data group by subscription_status 
order by Avg_amount, total_amount desc;

## Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, (100 * sum( case when discount_applied ='yes' then 1 else 0 end)/count(*)) as discount_rate from customer_data
group by item_purchased
order by discount_rate desc limit 5;

##Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (select previous_purchases, case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
Else 'loyal' end as customer_segment from customer_data)
select customer_segment, count(*)  as 'Number of customers' from customer_type 
group by customer_segment;

## Q8. What are the top 3 most purchased products within each category?

with item_count as (select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data group by category, item_purchased)
select category, item_purchased, total_orders from item_count where item_rank <=3;

##--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?'

select subscription_status, count(customer_id) as repeated_buyers
 from customer_data where previous_purchases >5 
 group by subscription_status;


##--Q10. What is the revenue contribution of each age group?

select sum(purchase_amount),age_group 
from customer_data group by age_group 
order by sum(purchase_amount) desc;
